# Generated by Django 2.1.7 on 2020-01-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='time',
        ),
    ]
